## Descriptive Statistics
Descriptive Statistics summaries a dataset, which helps in gaining insights, and making inferences about a dataset.

In general, we compute statistical measures of one or more samples, related to a population, and draw conclusions about the population.

Descriptive Statistics involves estimating centrality measures and measures of dispersion.

### Centrality Measures
Centrality measures determine the center of a dataset.

The three major centrality measures are: mean, median, and mode.

#### Mean

Mean is the sum of all values divided by a total number of values, of a data set.

mean function of numpy is used to compute mean marks obtained by five students in a subject s1.

In [1]:
import numpy as np

s1 = np.array([86, 47, 45, 47, 40])
print(np.mean(s1))

53.0


### Median
#### Median

Median is the value that separates the given data set into two halves.

median function of numpy library can be used to compute median of a data set, as shown here,

In [2]:
import numpy as np

s1 = np.array([86, 47, 45, 47, 40])
print(np.median(s1))

47.0


### Mode
#### Mode

The value that appears most often in a dataset is called the mode value.

mode function of scipy.stats module can be used for computing mode of a given data set.

In [3]:
from scipy import stats
import numpy as np
s1 = np.array([86, 47, 45, 47, 40])
print(stats.mode(s1))

ModeResult(mode=array([47]), count=array([2]))


If there are more than a single value, then only the first one is returned by mode function.

### Measures of Dispersion
Measures of Dispersion provide insights on the spread of given dataset.

Major measures of dispersion are: range, percentile, inter-quartile range, standard deviation, variance, skewness, and kurtosis.

#### Range

Range is the difference between maximum and minimum values of the dataset.

In [4]:
import numpy as np
s1 = np.array([86, 47, 45, 47, 40])
print(np.ptp(s1))

46


### Percentile
#### Percentile

Percentile refers to a value, below which lies given the percentage of data points.

E.g., 45th percentile refers to a value below which 45% of data points are found.

percentile function of numpy can be used to compute a single or multiple percentiles.

In [6]:
import numpy as np

s2 = np.array([86, 47, 45, 47, 40, 97, 98, 75, 65, 83])
print(np.percentile(s2, 45, interpolation="lower"))

65


### Quartiles
#### Quartiles
Three Quartiles namely, Q1 Q2 and Q3, split the entire dataset into four equal parts.

Each part contains 25% of data.

In [8]:
import numpy as np

s2 = np.array([86, 47, 45, 47, 40, 97, 98, 75, 65, 83])
print(np.percentile(s2, [25,50,75], interpolation="lower"))

[47 65 83]


### Inter Quartile Range (IQR)
#### Inter Quartile Range (IQR)
Inter quartile range refers to difference between third quartile (Q3) and first quartile (Q1).

iqr method from scipy.stats can be used for calculating it.

In [9]:
from scipy import stats
import numpy as np
s2 = np.array([86, 47, 45, 47, 40, 97, 98, 75, 65, 83])
print(stats.iqr(s2, rng=(25,75), interpolation="lower"))

36


### Variance and Standard Deviation
#### Variance

Variance is defined as the average of squared differences, of each data point from dataset's mean.
#### Standard Deviation

Standard Deviation is square root of variance.

var and std functions of numpy can be used for computing variance and standard deviation respectively.

By default, the functions assume that the dataset represents entire population.

To represent a sample, derived from a population, ddof parameter is set to 1.

In [10]:
import numpy as np

s2 = np.array([86, 47, 45, 47, 40, 97, 98, 75, 65, 83])

print(np.var(s2))
print(np.std(s2))

# s2 representing population's sample

print(np.var(s2, ddof=1))
print(np.std(s2, ddof=1))

454.21000000000004
21.312203077110542
504.6777777777778
22.46503455990615


### Skewness
#### Skewness

skewness determines whether the majority of data points are present on one side of the distribution.

A positive value represents right skewed distribution; a negative value represents left skewed one, zero represent unskewed distribution.

In [11]:
from scipy import stats
import numpy as np

s2 = np.array([86, 47, 45, 47, 40, 97, 98, 75, 65, 83])

print(stats.skew(s2))


0.04321019390325423


### Kurtosis
#### Kurtosis

Kurtosis indicates how much of data is concentrated around mean or shape of the probability distribution.

It can be estimated using kurtosis function of scipy.stats module.

By default, it uses Fisher’s definition. This can be changed to Pearson by setting fisher parameter to False.

In [12]:
from scipy import stats
import numpy as np

s2 = np.array([86, 47, 45, 47, 40, 97, 98, 75, 65, 83])

print(stats.kurtosis(s2))


-1.5694354898634155


## Random Numbers

A random number is a number, chosen by chance from a distribution.

Python provides a lot of modules, which deal with random numbers.

random module of python standard library.
random module of Numpy
stats module of Scipy

### Numpy's Random Module
random module of numpy has utilities, which generate arrays of random numbers.

E.g.: rand function generates uniformly distributed numbers from range [0, 1)

rand function with no arguments generate a single random value.

By passing arguments, it generates a random array of specified size.



In [13]:
import numpy as np
print(np.random.rand())

# generate a 2*3 array
print(np.random.rand(2,3))

0.4900993583912884
[[0.8719898  0.40329016 0.80696628]
 [0.5683743  0.01408348 0.14694919]]


### Random Sampling

In statistics, you select items randomly from a population, either with or without a replacement.

This can be achieved with choice method as shown below.

In [16]:
import numpy as np

print(np.random.choice([11,2,33], replace=False))

33


### Random Seeding
Seed is an important concept when it comes to reproducibility. If you are working with random numbers and you would want to peers to validate your results, i.e., they should also get the same random sequence as you did, you can set the seed to a particular value and send the seed value to your peers.

seed is a number that sets the initial state of random number generator.

Setting a seed, helps in generating the same sequence of random numbers, repeatedly.

seed method of a random module can be used to set a seed as shown in below example.

In [17]:
import numpy as np
np.random.seed(100)
print(np.random.rand())

np.random.seed(100)
print(np.random.rand())

0.5434049417909654
0.5434049417909654


### Random Variables
In probability theory, the set of all possible outcomes of a random experiment is known as sample space.

Probabilities of all outcomes of the experiment define the probability distribution.

A random variable is a variable that takes real numbers or integers and map each value to one of the outcomes of sample space.

E.g.: In an experiment of tossing a coin, the sample space is {'Head', 'Tail'} and a possible random variable takes the value 0 for head and 1 for the tail.

### Probability Distributions
There are two types of probability distributions namely discrete and continuous that take integer and real values, respectively.

scipy.stats module provides classes that represent random variables, corresponding to a large number of probability distributions.

E.g: the class norm represent normal continuous random variable, and binom represent binomial discrete random variable.

### Random Distributions
scipy.stats module provide a lot of methods for created discrete and continuous random variables.

Commonly used methods are described below.

 - pdf / pmf : Probability distribution function (continuous) or probability mass function (discrete).
 - cdf : Cumulative distribution function.
 - sf : Survival function (1 – cdf).
 - rvs : Creating random samples from a distribution.

### Random Distributions
The following example defines a normal continuous random variable of mean 1.0 and std 2.5.

It also estimates probabilities and cumulative probabilities at -1, 0 and 1.

The example also generates six random numbers from defined normal distribution.

In [ ]:
from scipy import stats

x = stats.norm(loc=1.0, scale=2.5)

print(x.pdf([-1, 0, 1]))

print(x.cdf([-1, 0, 1]))

print(x.rvs((2,3)))

In [18]:
from scipy import stats

x = stats.norm(loc = 1.0, scale=2.5)

print(x.pdf([-1,0,1]))

print(x.cdf([-1,0,1]))

print(x.rvs((2,3)))

[0.11587662 0.14730806 0.15957691]
[0.2118554  0.34457826 0.5       ]
[[-0.40409689 -3.12269376  1.88668613]
 [-0.96516083  0.42031951  1.5199392 ]]


### Hypothesis Testing
Hypothesis Testing is a methodology for evaluating if a claim is acceptable or not, based on data.

In a Hypothesis Testing, a Null Hypothesis (Ho) represents currently accepted the state of knowledge, and an Alternative Hypothesis (Ha) represents a new claim which challenges the currently accepted state of knowledge.

The null hypothesis and the alternative hypothesis are mutually exclusive.

### Steps Involved in Hypothesis Testing
The following steps are involved in a Hypothesis Testing:

 - Define the null hypothesis and the alternative hypothesis.

 - Select a test statistics whose probability distribution function can be found under the null hypothesis.

 - Collect data.

 - Compute the test statistics from the data and calculate its p-value under the null hypothesis.

 - Null hypothesis is rejected if the p-value is lower than predetermined significance value.

### Choosing Test Statistics
In hypothesis testing, selecting a test statistics is the most difficult part.

The methods used for performing t-test are shown below.

 - stats.ttest_1samp: Tests if the mean of a population is a given value.
 - stats.ttest_ind: Tests if the means of two independent samples are equal.
 - stats.ttest_rel: Tests if the means of two paired samples are equal.

#### Example 1
Let's consider a common hypothesis: Mean of a population is equal to certain value.

 - In reality, we estimate mean and variance of a sample and calculate the test statistic.

 - If population variance is identified, then it is reasonable to consider that test statistic is normally distributed.

 - If population variance is unknown, sample variance is used, and test statistic follows t distribution.

#### Example 1
Consider a normal population with mean 0.8 and standard deviation 0.5.

Define the null hypothesis as Mean of the population is 1.0.

Let's calculate t-statistic and p-value

In [19]:
from scipy import stats
import numpy as np

mu, sigma = 0.8, 0.5
X = stats.norm(mu,sigma)

# Deriving a sample
n = 100
X_sample = X.rvs(n)


# Computing test statistic
t,p = stats.ttest_1samp(X_sample,1.0)
print(t,p)

-4.6096766186175335 1.2053870608536614e-05


### Example 1
In previous example, the obtained t-statistic value is -4.99 and p-value is 0.0000025.

Since p-value is very low and less than the significance level 0.05, you can reject the null hypothesis and infer that the mean of the population is not 1.

### Example 2
Let's consider another problem, where the null hypothesis states that the population means of two random variables are equal.

The below example derives two samples from different populations and verifies the claim that their population means are equal.

In [22]:
X1 = stats.norm(0.25,1.0)
X2 = stats.norm(0.50,1.0)

X1_sample = X1.rvs(100)
X2_sample = X2.rvs(100)

t,p = stats.ttest_ind(X1_sample,X2_sample)
print(t,p)

-0.01580161646661329 0.9874085697378898


### Example 2
In previous example, the obtained t-statistic value is -3.126 and p-value is 0.002.

Since p-value is very low and less than the significance level 0.05, you can reject the null hypothesis and state that population means of both samples differ.

### Statistical Model
A Statistical Model is a mathematical equation, which explains the relationship between dependent variables (Y) and independent variables (X).

In general, a model is written as

Y = f(X)

However, in reality, an element of uncertainty is expected due to factors such as measurement noise. Hence the aforementioned equation can be rewritten as

Y = f(X) + e   'e' is residual error

### Statistical Modelling
 - Statistical Modelling deals with creating models that attempt to explain the data best.

 - The simplest model is a linear model represented as Y = B0 + B1*X + e, where the coefficients, B0 and B1 are the parameters of the model and e is normally distributed residual error.

 - A linear regression model assumes that residuals are independent and normally distributed.

 - The model is fitted to data using ordinary least squares approach.

### Linear Models
 - In most of the linear regression models, a dependent variable y is written as :
 - a linear combination of the response variables X i.e y = B0 + B1*X1 + ... + Bn*Xn, or
 - functions of the response variables i.e y = B0 + B1*X + B2*x^2 + ... + Bn*X^n, or
 - models that have a linear component i.e y = B0 + B1*sin(X1) + B2*cos(X2)

### Non-Linear Models
 - Other than linear regression models, statistical modeling can be used to build non-linear models.

 - Errors of dependent variable follow a distribution other than normal distribution.

 - Examples of non-linear models are: Binomial Regression and Poisson Regression.

 - In most of the cases, the non-linear models are generalized to linear models.

### Design Matrices
 - In reality, you choose a model and fit the available data to it.

 - Once a model is chosen, design matrices y and X are constructed, and the regression problem is written, in matrix form, as y = XB + e.

 - where y is the vector of dependent variables, X is the vector of independent variables, B is a vector of coefficients, and e is the residual (error).

 - Thus obtained design matrices are passed as inputs to the chosen model.

### Statistical Modelling with StatsModels
 - statsmodels library supports several types of statistical models.

 - All of them follow a similar usage pattern.

 - A Statistical model is represented by a model class.

 - A model can be initiated with,

    - given design matrices of dependent and independent variables, or with
    - given patsy formula and data frame or dictionary-like object.

### Step 1: Creating a Model
An instance of a model class is created in either of the following ways.

 - model = sm.MODEL(y, X) or
 - model = smf.model(patsy_formula, data)
where MODEL and model refer to model names such as OLS, GLM, ols, glm, etc.

Uppercase names take design matrices as arguments, and lowercase names take Patsy formulas and data frames as arguments.

### Step 2: Fitting a Model
In order to fit the model with data, fit method is invoked on the created model, as shown below.

 - result = model.fit()
 
The fit method returns a result object, which has methods and attributes for further analysis.

### Step 3: Viewing Model Summary
The summary method of result object produces a summary text that describes the result of the fit, as shown below.

 - print(result.summary())
    
The displayed summary text varies for each statistical model and provides information of various statistical parameters.

### Step 4: Analyzing the Model Further
Other than viewing summary statistics, you can perform activities like,

  - Determining fitted values,
  - Predicting the dependent variable values for new independent variable values.
  - Checking if residuals of fitted models follow a normal distribution or not.

### Constructing Design Matrices
The below example shows calculation of design matrices, y, and X, for the considered linear model Y = B0 + B1*X1 + B2*X2 + B3*X1*X2.

In [ ]:
import numpy as np

y = np.array([1, 2, 3, 4, 5])
x1 = np.array([6, 7, 8, 9, 10])
x2 = np.array([11, 12, 13, 14, 15])
X = np.vstack([np.ones(5), x1, x2, x1*x2]).T

print(y)
print(X)

In [24]:
import numpy as np

y = np.array([1,2,3,4,5])
x1 = np.array([6,7,8,9,10])
x2 = np.array([11,12,13,14,15])
X = np.vstack([np.ones(5), x1, x2, x1*x2]).T

print(y)
print(X)

[1 2 3 4 5]
[[  1.   6.  11.  66.]
 [  1.   7.  12.  84.]
 [  1.   8.  13. 104.]
 [  1.   9.  14. 126.]
 [  1.  10.  15. 150.]]


Thus obtained design matrices (y and X) can be passed to regression methods for obtaining the coefficient vector.

### Design Matrices with patsy
 - patsy, a python library, allows defining a model in simpler easily.

 - It also constructs relevant design matrices, automatically, using patsy.dmatrices function.

 - patsy.dmatrices takes a formula (in string form) as a first argument, and a dictionary-like object with data arrays for the response variables as second arguments.

### Patsy Design Matrices
An example of using patsy.dmatrices function is shown below.

In [25]:
import patsy
import numpy as np

y = np.array([1, 2, 3, 4, 5])
x1 = np.array([6, 7, 8, 9, 10])
x2 = np.array([11, 12, 13, 14, 15])
data = {'y':y, 'x1':x1, 'x2':x2}

y, X = patsy.dmatrices('y ~ 1 + x1 + x2 + x1*x2', data)

print(y)
print(X)

[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]
[[  1.   6.  11.  66.]
 [  1.   7.  12.  84.]
 [  1.   8.  13. 104.]
 [  1.   9.  14. 126.]
 [  1.  10.  15. 150.]]


### Understanding patsy Formulae
Let's understand few patsy formulae provided below.

 - 'y ~ x' : y is linearly dependent on x. ~ symbol separates dependent variable from independent variable terms. It is also equivalent to 'y ~ 1 + x'.

 - 'y ~ x1 + x2' : y is a linear combination of x1 and x2. + sign is used to denote the union of terms.

 - y ~ x1*x2 : x1*x2 is an interaction term that includes all lower order terms. Hence formula is equivalent to y ~ 1 + x1 + x2 + x1*x2.

### Understanding patsy Formulae
 - 'y ~ np.log(x1)': Often numpy functions can be used to transform terms in the expression.

 - 'y ~ I(x1 + x2)': I is the identify function, used to escape arithmetic expressions and are evaluated.

 - 'y ~ C(x1)': Treats the variable x1 as a categorical variable.

### Example Datasets
 - statsmodels contain few popular example datasets, which can be used to explore various utilities of the package.

 - The example data sets are available in datasets module.

 - Each dataset is associated with special variables like SOURCE, DESCSHORT, DESCLONG, that provide more info about the dataset.

 - A dataset can be loaded using load function, and its data can be accessed using data attribute in the form of Numpy's recarray.

### Loading Example Datasets
The below example shows loading of popular breast cancer dataset and accessing its data as numpy array.

In [ ]:
import statsmodels.api as sm

bc_cancer_set = sm.datasets.cancer

bc_cancer = bc_cancer_set.load()

bc_cancer_data = bc_cancer.data

print(type(bc_cancer_data))

In [26]:
import statsmodels.api as sm

bc_cancer_set = sm.datasets.cancer

bc_cancer = bc_cancer_set.load()

bc_cancer_data = bc_cancer.data

print(type(bc_cancer_data))

<class 'pandas.core.frame.DataFrame'>


### Loading R Datasets
statsmodels package provides access to many example datasets of R, listed at R Datasets repository

The below example loads Icecream dataset from Ecdat package.

In [31]:
from scipy import stats
print(stats.mode([8, 9, 8, 7, 9, 6, 7, 6]))

ModeResult(mode=array([6]), count=array([2]))


In [32]:
from scipy.stats import f

p = 2
q = 27
f_statistic = 1

cum_prob = 1 - f.cdf(f_statistic, p, q)
print(cum_prob)

0.3810990309947886
